### ISSUE TITLE
"release":null for game coming from custom libraries plugin like MultiMC Library Importer or Riot Games Library

### ISSUE THREAD

**Issue by Shayviri** [andrew-codes/playnite-web#607] opened 2024-11-02 14:20 UTC
Hello,

I don't know if I am doing something wrong or if it has been already answered. I am sorry if it's the case.
I have noticed that when we launch a game with Playnite that come from custom libraries plugin like MultiMC Library Importer or Riot Games Library, the release is null throwing an error:

```
playnite-web/game-db-updater/handler/persistGameReleaseState Received game release state for topic playnite/playnite/response/game/state with payload {"release":null,"state":"launching"}
TypeError: Cannot read properties of null (reading 'id')
    at /opt/playnite-web-app/server.production.js:963:63048
    at /opt/playnite-web-app/server.production.js:963:64394
    at Array.map (<anonymous>)
    at xu.<anonymous> (/opt/playnite-web-app/server.production.js:963:64387)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

I tried with minecraft and league of legend. I don't know for manual import, though.

Anyway, it is an amazing project, really. I have seen that somebody is working on an HASS integration which is great! I saw this error while trying to control my Playnite instance with HASS too. I hope those projects will grow even more.
Thanks for your hard work!

**Comment by andrew-codes** [comment] 2024-11-02 14:36
I'm out of town but will look into it this upcoming week. I may reach out for additional details to troubleshoot.

**Comment by Shayviri** [comment] 2024-11-02 15:36
Sure, no problem

**Comment by Shayviri** [comment] 2024-11-03 13:25
Hi,
I will be away of my server in the next 2 weeks, so I will give you as much information as I can now for you to have material to troubleshoot if you want during this time.
When I check the number of games reported by Playnite including the hidden games, it shows 342 games. Without hidden games, it's 334. 
When I look into the mongodb under the database "games" in the collection "release", it shows 315 releases. 
I guess there are games that are not caught by the playnite web app. 

I have 6 minecraft instances, 4 from Prism Launcher that I add with MultiMC Library Importer plugin and 2 from the Xbox app. None are registered in the mongodb, so it's not only a plugin problem.
All games added with Riot Games Library plugin (3 games: League of legends, Legends of Runeterra and Valorant) aren't in the mongodb.
I didn't add any games manually, so everything come from the regular libraries + the 2 plugins I mentioned.

When I try to check which other games are not caught, I realeased that none of my game coming from xbox app are in the mongodb. I had at some point the xbox pass, but not any more. The games I played before are still in my xbox library which explain why they appear in playnite. However games like for example "Microsoft Solitaire Collection" is part of the xbox library and is in playnite. This is installed, and I can play it, but it doesn't appear in the mongodb. So I guess there are problems with the games coming from xbox library.

Here is the list I get when I check the mongodb under the database 'games' under the collection 'source' in case you need:
`[{'_id': ObjectId('67256bf5cd75f5e27e60efd7'), 'id': '6fffec81-a8ff-4cd7-8a02-4e620875d2b6', '_type': 'GameSource', 'name': 'EA app'}, {'_id': ObjectId('67256bf5cd75f5e27e60efd8'), 'id': 'b1bc024b-83d5-4cd6-a56d-326eeaeac68f', '_type': 'GameSource', 'name': 'Xbox'}, {'_id': ObjectId('67256bf5cd75f5e27e60efd9'), 'id': 'b23c7d60-4383-4d15-9f22-67936b34456f', '_type': 'GameSource', 'name': 'Battle.net'}, {'_id': ObjectId('67256bf5cd75f5e27e60efda'), 'id': '960c42c5-b84a-4659-9f40-8b93bb2e0a42', '_type': 'GameSource', 'name': 'Steam'}, {'_id': ObjectId('67256bf5cd75f5e27e60efdd'), 'id': '96baeffc-7245-4184-b602-25f470291bbc', '_type': 'GameSource', 'name': 'Epic'}, {'_id': ObjectId('67256bf5cd75f5e27e60f027'), 'id': '771c6d8a-1384-41f1-8db8-2e9fccc29155', '_type': 'GameSource', 'name': 'Riot Games'}, {'_id': ObjectId('67256bf6cd75f5e27e60f0d7'), 'id': '9da2fdf6-21e4-43c4-bfe0-91fce9da9d1d', '_type': 'GameSource', 'name': 'GOG'}]`

Let me know if you need more information, I might be able to answer without needing access to the server, and if it is needed I can answer when I come back.

**Comment by Shayviri** [comment] 2024-11-09 13:18
Thanks a lot for your reply.

I have partial remote access to my server. So I can reply several of your questions.

For the solution for Riot Games, I will do it when I am back to have a full control on things and give you proper feedback.

For the MultiMC Library, the games added using this plugin doesn't have source or platform, which might explain why they are not considered by the playnite web app. The only metadata available are the name, the installation path and a quick description with the minecraft version. Those are not emulated games afaik.

For the other games that are not considered by playnite web, actually, they are all from the Xbox game app. None of my games coming from the Xbox games app are in the mongo database. 
When I look on Playnite, they do have a platform like PC (Windows) or Mac or Linux and a source which is Xbox. 

Hope this help you! I will come back to you when I come back to give you feedback on the solution of Riot Games.
Thank you again!

**Comment by Shayviri** [comment] 2024-11-21 17:51
Hi again,

I came back and installed the playnite web plugin you gave. I synced my games and checked if any games of Riot games were in db.release. But none is there.
Let me know if you need any more information or data on this!

**Comment by andrew-codes** [comment] 2024-11-21 19:18
Hi, thanks for the reply. A feature to default unknown library sources to PC, #633, has been released. This will cover Riot and also other unrecognized sources and assign them as PC platform games. It is unclear if the core problem is due to a game release from an unknown source or something else. If the former, then the most recent release of Playnite Web may address the issue entirely.

Please try the newest version and report back if the starting of games is resolved. In the meantime, I intend to add additional logging to the Playnite Plugin to help troubleshoot this issue further. Thanks!

**Comment by andrew-codes** [comment] 2024-12-04 15:00
Note #654 may resolve this issue.

**Comment by andrew-codes** [comment] 2024-12-05 23:39
@Shayviri Can you try with 9.5.0 and report back if it does it did not address your problem. Thanks!

**Comment by andrew-codes** [comment] 2024-12-08 00:42
@Shayviri, try dropping your database and using version ^10.0.0. I suspect some of the sync messages may have been dropping and causing this issue. Please let me know if this resolves the issue.

**Comment by Shayviri** [comment] 2024-12-08 23:51
Hi, sorry for the late reply. I have reset entirely (reinstalling in new folder) and updated my mongo and playnite web containers. I also updated playnite web on playnite. When I try to sync my library on playnite, I have an error saying that the value "source" cannot be "null". Nothing appears on the log of my playnite-web container, so I guess it is only on the playnite app

**Comment by andrew-codes** [comment] 2024-12-09 00:26
Thanks @Shayviri , your issue is now a duplicate of #659. I'll track the "source is null" error there. Once it is resolved and released, we can revisit to see if this GitHub issue is still a problem. Thanks!

**Comment by andrew-codes** [comment] 2024-12-10 02:40
@Shayviri  now that #659 is resolved, please let me know if this is still a problem or if I can close this issue. Thanks.

**Comment by Shayviri** [comment] 2024-12-10 14:33
You did an amazing job tbh, and now you are catching the release:null error. You fixed the Riot games which have a not null release. 

In my use case, I am using your API start and stop to launch and stop a game on my computer. To use those API calls, we need the game ID. Before to use those start and stop API, I am actually scanning the database to get the release of all the game installed and save it. The thing is, games that have a release:null cannot be launched using the API because I don't have the game ID. Which means that is that case, for example, I cannot launch my instances of minecraft using this app. 

Now, can I live without it? Yes, completely. It is just a fun project where I want to be able to launch my game through home assistant. I can launch almost all my games. If I cannot launch some games this way, it's really not a problem.
I don't know how much of works and effort it needs to solve this issue, and maybe you want to focus on something else. So you can close this issue, I have no problem with it. But if you think it's worth it to try to solve it, I can help with testing!

**Comment by andrew-codes** [comment] 2024-12-10 15:56
Wow, that is awesome! I'm happy to hear it is working mostly well for you. My primary use case is also to automate launching games. I use Playnite Web on a phone or tablet as my over-powered remote control. I should write a blog post sometime soon, as I do not need to use the API at all to accomplish this, just the Playnite Web UI, Home Assistant, and the underlying start/stop/restart MQTT messages Playnite Web publishes.

As for whether to close this issue, I think I'll keep it open. Even though I do not have any games that match this use case, I'd like Playnite Web to be accessible and usable for others, which may very well have this exact same use case and problem. I do appreciate and welcome the help in testing and, really, diagnosing the root cause. Without this, I could not create a fix/solution, so thank you!

To gather more information on the problem:

What games, specifically, do not have a Release? I assume these can be found in Playnite, but are not synchronized to Playnite Web; is this correct? What are the games' names, source value, and associated platforms (from Playnite's side)?

Are there any properties of these games that are the same as far as you can tell? Same name, same series, same source, etc.? Were they all added in the same way (manually or some other mechanism)? I'm looking for a common thread.


Finally, would it interest you, or others, for me to outline my setup for using Playnite Web's UI to search and control playing games? I'm happy to share. Thanks again for your support!

**Comment by Shayviri** [comment] 2024-12-10 16:52
I am sorry, I am starting a bit in the network realm and I might have said something wrong. I am actually using MQTT messages to control the playnite web app, not API. I thought it was similar things, but I guess it is not. My bad, sorry, I am trying to learn and improve by actually doing those kinds of funny projects. 

So, I guess I am doing like you using MQTT messages and those MQTT messages need a payload where you specify the game ID, but with the games without release, it is not possible to extract those game ID, or maybe I don't do it properly.

AFAIK, the game that are not caught by playnite web are the games from the xbox app and the minecraft instances. Of course, all those game are able to be launch with playnite itself.

The xbox app games seams to have a platform (for example "PC (windows)"), a source ("xbox"), and a bunch of metadata, so I don't really know why playnite web is not able to create a release for them.

In the case of Minecraft instances, there are almost nothing on them. No platform, no source. When you set up the MultiMC/PolyMC/Prism plugin, you specify the location folder of the launcher like Prism launcher and the plugin will extract the different minecraft instances folder location and put it in playnite.

The reason I want to use home assistant to control my games is to integrate it with automations or scenes. But clearly I would be interrested in how you do it in your case. And I am sure a lot of people would be happy to see and deploy the same as you. So if you make a guide or soemthing like this, it would probably help a lot of people to see what can be done with you project!

**Comment by andrew-codes** [comment] 2024-12-30 21:14
Closing this. The new feature to enable more robust game to platform configuration for releases is tracked in #682

**Closed by andrew-codes** 2024-12-30 21:14 UTC
Labels: bug
