### ISSUE TITLE
Error installing plugin to Playnite from releases

### ISSUE THREAD

**Issue by erictbar** [andrew-codes/playnite-web#230] opened 2024-03-03 15:02 UTC
Greetings. I was looking for something like this and am glad to see someone made it.

Getting the error ``Extension "Playnite Web" failed to load property.`` after dragging the plugin (2.0 from release page) to Playnite and restarting the app. Same issue when trying 1.0 release.

Playnite logs:
[playnite.log](https://github.com/andrew-codes/playnite-web/files/14473420/playnite.log)
Notably:
```
03-03 09:23:39.027|ERROR|ExtensionFactory:Failed to load plugin: Playnite Web
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at PlayniteWeb.Services.ObjectSerializer..ctor()
   at PlayniteWeb.PlayniteWeb..ctor(IPlayniteAPI api) in C:\Users\andrew\developer\repos\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 60

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
Workaround:
I compiled the plugin with VS 2022, when asked I updated .NET to 4.8, copied the files from ``PlayniteWeb\apps\PlayniteWebPlugin\.dist\bin\Debug`` to ``%APPDATA%\Playnite\Extensions\PlayniteWeb_ec3439e3-51ee-43cb-9a8a-5d82cf45edac`` and the plugin opened.

Now, I still need to configure the server.

**Comment by 2600box** [comment] 2024-04-04 13:17
- Hello @erictbar I have the same issue. Would you share your .perf file please? Cheers!

```
03-04 20:18:07.408|ERROR|ExtensionFactory:Failed to load plugin: Playnite Web
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at PlayniteWeb.Services.ObjectSerializer..ctor()
   at PlayniteWeb.PlayniteWeb..ctor(IPlayniteAPI api) in C:\Users\andrew\developer\repos\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 60

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

**Comment by andrew-codes** [comment] 2024-04-09 19:28
I found the root issue. There is a Playnite tool, named Toolbox, that packs extensions for distribution.  It appears to ignore files when packing; found in a file within the installation's templates directory; see [code doing this work](https://github.com/JosefNemec/Playnite/blob/5d7838951485db1824c39c6db472982222300fd2/source/Tools/Playnite.Toolbox/Paths.cs#L52) and the [ignored file list](https://github.com/JosefNemec/Playnite/blob/5d7838951485db1824c39c6db472982222300fd2/build/ExtensionsRefIgnoreList.txt#L9). I didn't realize this, but Netwonsoft's dll is one of those ignored files. For this reason, the packaged extension is missing some of its files, which is the reason for the error message provided.

I never noticed this behavior, as I was installing locally on top of existing extensions for development, which already had the dll file in place.

It is unclear to me why this is ignored, but I imagine there is a good reason. It could be to prevent collisions of dependencies in use by Playnite that could be different versions than an extension. I think this may be corroborated by the [fact that version 10.0.3](https://github.com/JosefNemec/Playnite/blob/5d7838951485db1824c39c6db472982222300fd2/source/Playnite/packages.config#L19) is a dependency of Playnite itself.

As to a fix, I'm thinking the easiest solution is to use a different library that serves the same purpose. I will work on this soon and release a new patch version update.

**Comment by 2600box** [comment] 2024-04-10 08:08
Great to hear that you found the root cause. I would love to be able to see this project develop quickly. It is surprising to me that a web interface is not a core component of Playnite, but I prefer your solution anyway, as I use a dedicated gaming PC that is not turned on most of the time, but run a lot of self-hosted services on linux.

The version of Playnite I am using is:
Playnite 10.32
SDK: 6.11.0
Theme API: 2.6.0

I had never used VSCode before, but I stumbled my way through and built the plugin locally and indeed it works.

**Comment by andrew-codes** [comment] 2024-04-11 12:08
Note to self: favor the use of https://api.playnite.link/docs/api/Playnite.SDK.Data.Serialization.html over Netwonsoft

**Comment by andrew-codes** [comment] 2024-04-11 13:43
Fixed in [2.0.1 release](https://github.com/andrew-codes/playnite-web/releases/tag/2.0.1). Thanks!

**Comment by 2600box** [comment] 2024-04-14 18:11
Hi, I had a chance to try 2.0.1 just now. I uninstalled the version of the plugin that I had and installed your 2.0.1 file.

It installs fine, and shows as enabled. It also shows as version 0.1 within Playnite...

It fails, however, when selecting "sync library" with the message `Serialization and deserialization of 'System.Type' instances is not supported. Path: $.BuiltinProfiles.Type.`

Here is the log:

```
14-04 20:04:42.625|ERROR|MainMenu:Main menu extension action failed.
System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported. Path: $.BuiltinProfiles.Type. ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsObject(Utf8JsonWriter writer, Object rootValue)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at PlayniteWeb.Services.ObjectSerializer.Serialize(Object data) in C:\Users\andrew\developer\repos\playnite-web\apps\PlayniteWebPlugin\src\Services\ObjectSerializer.cs:line 9
   at PlayniteWeb.Services.Publishers.Mqtt.PublishGameEntity.<Publish>d__5.MoveNext() in C:\Users\andrew\developer\repos\playnite-web\apps\PlayniteWebPlugin\src\Services\Publishers\Mqtt\PublishGameEntity.cs:line 29
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at PlayniteWeb.PlayniteWeb.SyncLibraryFromMenu(MainMenuItemActionArgs args) in C:\Users\andrew\developer\repos\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 152
   at Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass17_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\MainMenu.cs:line 378
```

**Comment by andrew-codes** [comment] 2024-04-16 21:57
I've re-opened the issue and will investigate it this week. I have not seen this issue working with my local Playnite; which is making me wonder if there is something about the data itself that is causing a problem. As a side note, I will prioritize adding more capabilities to troubleshoot issues from other's installations. This may also help troubleshoot this problem. If it is indeed data related, I would love to know what data is causing the issue. The only way to know this without getting a dump of the entire Playnite database (which I feel is an unreasonable ask), is to have better logging. Thanks, and stay tuned. @2600box , I may ask for you to use a new patch version with better logging and report back, if that is ok. I'll keep this issue updated as things progress. Thanks!

**Comment by 2600box** [comment] 2024-04-17 07:04
Happy to test. It continues to work from my locally built version of the plugin.

**Comment by andrew-codes** [comment] 2024-04-19 21:07
@2600box , I have included some logging to see which game related entity it is breaking on for you. If you please, download and try the playnite extension from this workflow: https://github.com/andrew-codes/playnite-web/actions/runs/8759529008. It will be a zip file at the bottom of the workflow named playnite-extension.

You should notice the version reported in Playnite is now different than 0.0.1. Please post back the results and any log messages you receive relating to the extension. Hopefully, this will aid in tracking down the issue as I cannot reproduce myself. Thanks again!

**Comment by 2600box** [comment] 2024-04-25 09:21
Hello, I had a chance to try your pext release 3.0 bit still having the same problem... It installs fine, is recognised as version 3.0, but fails with this error when initiating the sync.

![playnite-web](https://github.com/andrew-codes/playnite-web/assets/6595566/1bdbea84-7d10-4595-afc1-e732436ca479)

extensions.log

```
25-04 11:13:46.704|ERROR|PlayniteWeb#ObjectSerializer:Serializing Dolphin - System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported. Path: $.BuiltinProfiles.Type. ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsObject(Utf8JsonWriter writer, Object rootValue)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at PlayniteWeb.Services.ObjectSerializer.Serialize(Object data) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Services\ObjectSerializer.cs:line 13
```

playnite.log

```
25-04 11:13:38.211|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.AddonsWindowFactory: 46be16af-dd13-4c80-b3aa-a7d584d38e9c, True
25-04 11:13:46.704|ERROR|MainMenu:Main menu extension action failed.
System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported. Path: $.BuiltinProfiles.Type. ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at PlayniteWeb.Services.ObjectSerializer.Serialize(Object data) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Services\ObjectSerializer.cs:line 18
   at PlayniteWeb.Services.Publishers.Mqtt.PublishGameEntity.<Publish>d__5.MoveNext() in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Services\Publishers\Mqtt\PublishGameEntity.cs:line 29
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at PlayniteWeb.PlayniteWeb.SyncLibraryFromMenu(MainMenuItemActionArgs args) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 152
   at Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass17_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\MainMenu.cs:line 380

```

**Comment by 2600box** [comment] 2024-04-26 09:59
I made a pull request for what seems to resolve the errors... 

https://github.com/andrew-codes/playnite-web/pull/266

**Closed** 2024-04-26 12:36 UTC
Labels: bug, triage
